version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5
    ports:
      - 80:80
      - 8080:8080
    volumes:
      # Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      # Enables the web UI
      - --api.insecure=true
      # Tells Traefik to listen to docker
      - --providers.docker
      # Creates a new entrypoint called web
      - --entrypoints.web.address=:80
    networks:
      - selling-point
  api:
    build: 
      context: ./selling-point-api
    labels:
      # Tells Traefik where to redirect the request if the url has the specified prefix
      - traefik.http.routers.api.rule=PathPrefix(`/api`)
      - traefik.http.routers.api.middlewares=auth-forward-auth
      - traefik.http.routers.api.entrypoints=web
    volumes:
      - ./selling-point-api/src:/app/src
    networks:
      - selling-point
  auth:
    build: 
      context: ./selling-point-auth
    labels:
      # Tells Traefik where to redirect the request if the url has the specified prefix
      - traefik.http.routers.auth.rule=PathPrefix(`/auth`)
      - traefik.http.middlewares.auth-forward-auth.forwardauth.address=http://auth:3000/auth/authorize
      - traefik.http.routers.auth.entrypoints=web
    volumes:
      - ./selling-point-auth/src:/app/src
    networks:
      - selling-point

networks:
  selling-point:
    name: selling-point
    driver: bridge